version: "3.8"

services:
  web:
    container_name: recipes
    build: .
    command: sh startup.sh
    ports: 
      - 8000:8000
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    container_name: recipes_db
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

volumes:
  postgres_data: